

const FETCH_STORIES_SUCCESS = 'FETCH_STORIES_SUCCESS'
const HANDLE_CHANGE_INPUT = 'HANDLE_CHANGE_INPUT'
const HANDLE_NEXT_PAGE = 'HANDLE_NEXT_PAGE'
const HANDLE_PREV_PAGE = 'HANDLE_PREV_PAGE'
const HANDLE_REMOVE_STORY = 'HANDLE_REMOVE_STORY'
export {
    FETCH_STORIES_SUCCESS, HANDLE_CHANGE_INPUT,
    HANDLE_NEXT_PAGE, HANDLE_PREV_PAGE,
    HANDLE_REMOVE_STORY
}
